### PR TITLE
Fix Compile Problem

### PR DESCRIPTION
**Pull request by Yannnnnnnnnnnn**
I have test this under two computers in Ubuntu16.04 System and it works.
But it will be better if you look into these changes, because I am not familiar with the CMakeLists.txt

### CODE REVIEW

**Comment by learnccode** [comment]
抱歉之前工作忙，没有及时回复。我们之前用的openMVG库的确不是最新版的，谢谢你修复了我们的bug，我们会尽快重新更新代码。

**Comment by learnccode** [comment]
Thank you for your work. We will update the code as soon as possible. @Yannnnnnnnnnnn

**Comment by RemoteSensingFrank** [comment]
Thanks for your cooperation and I've read all the changes. I wonder that the does problem caused by the version ofopenmvg, for the header cited in my own program can be compiled successfully. And by the way would you mind be a co-dev for the project.

**Comment by Yannnnnnnnnnnn** [comment]
Maybe you install the openMVG in the /usr/local/, and I just put the  openMVG in a normal folder, which means I don't have any ENV_VAR pointing to the openMVG.
Besides, I am very glad to be a co-dev of the project.

**Comment by RemoteSensingFrank** [comment]
I send collaborator inviation to you.And I hope that we can code in the likely style, by the way I will add some explanation for the key block.

**Comment by Yannnnnnnnnnnn** [comment]
I have add a .travis.yml and PASS the test on Travis CI

**Comment by Yannnnnnnnnnnn** [comment]
@RemoteSensingFrank I don't receive your collaborator inviation, would you mind to send that to me one more time?

**Comment by RemoteSensingFrank** [comment]
the invitation shared link is https://github.com/RemoteSensingFrank/UAVProduct/invitations

**Pull request merged**
